# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        vignette:
            filters:
                thumbnail: { size:  [120, 90], mode: outbound}
                background: { size:  [120, 90] , postion: center, color: '#000000' }
        product_show:
            filters:
                thumbnail: { size: [ 240, 180 ], mode: outbound }
                background: { size: [ 250, 190 ] , postion: center, color: '#000000' }
        product_index:
            filters:
                thumbnail: { size: [200, 150 ], mode: outbound }
                background: { size: [ 205, 155 ] , postion: center, color: '#000000' }

