twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        test_variable: '@App\Service\CoucouService'

when@test:
    twig:
        strict_variables: true
